manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.2.0   # <-- 2年前の安定版「v3.2.0」に固定します
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main       # <-- この部品は2年前に更新が止まっているので、v3.2.0と互換性があるはずです
  self:
    path: config
