manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inorichi # kumamuk-git の代わりに、v3.5対応版の作者を指定
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main # ZMK本体は最新のまま
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi # こちらも inorichi を指定
      revision: v3.5    # ZMK本体のバージョン(v3.5)に一致させます
  self:
    path: config
