manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.4   # 「.0」を削除し、「v3.4」に
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: v3.4   # 「main」から「v3.4」に
  self:
    path: config
